export default {
  add: "mdi-plus",
  arrow_drop_down: "mdi-menu-down",
  arrow_left: "mdi-chevron-left",
  arrow_right: "mdi-chevron-right",
  check: "mdi-check-circle",
  close: "mdi-close",
  copy: "mdi-content-copy",
  delete: "mdi-delete",
  edit: "mdi-pencil",
  error: "mdi-alert-circle",
  info: "mdi-information",
  keyboard_arrow_down: "mdi-chevron-down",
  keyboard_arrow_left: "mdi-chevron-left",
  keyboard_arrow_right: "mdi-chevron-right",
  keyboard_arrow_up: "mdi-chevron-up",
  lock: "mdi-lock",
  lock_open: "mdi-lock-open-variant-outline",
  menu_dots: "mdi-dots-vertical",
  prediction: "mdi-crystal-ball",
  question: "mdi-cloud-question",
  reflection: "mdi-mirror",
  statement: "mdi-chat-alert",
  success: "mdi-check-circle",
  update: "mdi-cached",
  url: "mdi-web",
  warning: "mdi-alert",
};
